-- TASK-34: alert rule seed placeholder
--
-- online_price_alert_rules.company_id is required, so global seed rows with
-- NULL company_id fail on Supabase/Postgres. Default rules must be created by
-- application code for a concrete company_id.
